### ISSUE TITLE
error

### ISSUE THREAD

**Issue by tianbinraindrop** [itldg/vscode-ldggist#1]
![图片](https://user-images.githubusercontent.com/15842116/162594712-da041f0a-4a57-47b8-ab78-036ff75fef11.png)

**Comment by itldg** [comment]
是否已经恢复了呢?

**Comment by itldg** [comment]
太久没有收到答复,如果错误已经修复或者没有再产生过错误,我要关闭这个Issues了,如果后续有问题您可以重新打开
